### ISSUE TITLE
RFI

### ISSUE THREAD

**Issue by gotspatel** [palinkas-jo-reggelt/GeoIP_Server#1]
Greetings,

Can you please inform how to use it/how to implement?

Regards

**Comment by palinkas-jo-reggelt** [comment]
Sure. Its just a php website. You have to have maxmind database to draw the data from. 

There are 2 pages. index.php and api.php. Both use url rewrites to shorten/simplify the url. The index.php page is a visual page that includes a map. The api.php page is json only.

index.php:
`/map/<Valid-IPv4-or-IPv6>` will return the requested IP.
`/map/<Valid-Reserved-IPv4-or-IPv6>` will return "Reserved IP" with a link to your own IP data.
`/` will return your IP.
`/<anything>` will return your IP.

api.php:
`/api/<Valid-IPv4-or-IPv6>` will return json string for requested IP.
`/api/<Valid-Reserved-IPv4-or-IPv6>` will return json error string ("reserved address").
`/api/<anything>` will return json error string ("invalid ip").

**Comment by gotspatel** [comment]
any pointer how to modify it to work for 

`http://localhost:8094/index.php/map/137.184.170.2`

I am on IIS and my web are with different ports rather then sub website, please

I am using your geoiptosql already for hmail

**Comment by gotspatel** [comment]
OKAY FOUND SOLUTION for IIS with port numbers.
::for JSON:::
http://localhost:8094/api.php?geoip=137.184.170.2

:::for MAP:::
http://localhost:8094/index.php?geoip=137.184.170.2

**Comment by gotspatel** [comment]
this is for situation where you don't want to edit the .htaccess file

**Comment by palinkas-jo-reggelt** [comment]
No, sorry. I don't know enough about IIS. This is meant for apache - a critical component is the htaccess file that handles the url rewrites.

Anyway, why keep it hidden on localhost:weirdport? It doesn't do anything except display publicly available data. It doesn't write anything. Its meant to be shared with the world. :-)

**Comment by gotspatel** [comment]
Sorry Sir,

I think you didn't read my reply. (SOLUTION for IIS) :-)

Thank you for sharing all the wonderful solutions. as always

Regards
